feat(errors): Provide context on compile errors
This is working to address #105 (location) and #114 (lock down error api).

Example error:
```
Error: parse error: Snippet does not exist
cause: No such file or directory (os error 2)
  with:
    non-existent source=""
from: {% include blue %}
from: {% for i in (1..max) reversed %}
from: {% if 5 == var %}
```